repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v6.0.0"
    hooks:
      - id: trailing-whitespace
        stages:
          - pre-commit
      - id: end-of-file-fixer
        exclude: ^secrets
        stages:
          - pre-commit
      - id: check-yaml
        stages:
          - pre-commit

  - repo: https://github.com/gitleaks/gitleaks
    rev: "v8.28.0"
    hooks:
      - id: gitleaks
        stages:
          - pre-commit

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.14.0"
    hooks:
      - id: ruff-format
        stages:
          - pre-commit
        exclude: ^tests/
      - id: ruff-check
        stages:
          - pre-commit
        args:
          - "--exit-non-zero-on-fix"
        exclude: ^tests/

  - repo: https://github.com/PyCQA/pylint
    rev: "v3.3.9"
    hooks:
      - id: pylint
        stages:
          - pre-commit
        exclude: ^tests/
        additional_dependencies:
          - "pydantic==2.12.5"
          - "pydantic-settings==2.12.0"
          - "pylint-pydantic==0.4.1"

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.18.2"
    hooks:
      - id: mypy
        stages:
          - pre-commit
        exclude: (^src/playground/|^examples/|^tests/|^alembic/)
        args:
          - "--explicit-package-bases"
          - "--namespace-packages"
          - "--ignore-missing-imports"
        additional_dependencies:
          - "pydantic==2.12.5"
          - "pydantic-settings==2.12.0"
          - "types-requests"
          - "pandas-stubs"
          - "types-python-jose"
          - "types-passlib"

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: "v9.23.0"
    hooks:
      - id: commitlint
        stages:
          - commit-msg

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.5
    hooks:
      - id: uv-sync
        args:
          - "--verbose"
